[package]
name = "virtfsd"
version = "0.1.0"
edition = "2024"

[dependencies]
fuser = "0.14"
tokio = { version = "1", features = ["rt-multi-thread", "signal", "macros"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = "0.11"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
virtfs-common = { path = "../virtfs-common" }
